package config

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// RenderReference renders the public configuration catalog without resolving
// environment or persisted values. Sensitive defaults are never included.
func RenderReference() []byte {
	fields := Catalog()
	sort.Slice(fields, func(i, j int) bool { return fields[i].Name < fields[j].Name })

	var output bytes.Buffer
	output.WriteString("<!-- Generated by go run ./internal/config/configdoc --write. Do not edit. -->\n\n")
	output.WriteString("# Configuration reference\n\n")
	output.WriteString("This table is generated from `config.Catalog()`. It describes supported settings, not the values active on your machine. It never resolves persisted settings, credentials, or environment values.\n\n")
	output.WriteString("Run `acd config get` to inspect effective repository settings and environment overrides. See [Settings](settings.md) for precedence and persistence details.\n\n")
	output.WriteString("| Setting | Environment variable | Default | Apply boundary | Can be persisted | Sensitive |\n")
	output.WriteString("|---|---|---|---|---|---|\n")
	for _, field := range fields {
		fmt.Fprintf(&output, "| `%s` | `%s` | %s | %s | %s | %s |\n",
			escapeTableCell(field.Name),
			escapeTableCell(field.Environment),
			referenceDefault(field),
			referenceBoundary(field.Boundary),
			yesNo(field.Persistable),
			yesNo(field.Sensitive),
		)
	}
	return output.Bytes()
}

func referenceDefault(field FieldDefinition) string {
	if field.Sensitive {
		return "not shown"
	}
	if field.Default == "" {
		return "none"
	}
	return "`" + escapeTableCell(field.Default) + "`"
}

func referenceBoundary(boundary ApplyBoundary) string {
	switch boundary {
	case ApplyHot:
		return "next work boundary"
	case ApplyRestart:
		return "restart required"
	default:
		return "unknown"
	}
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func escapeTableCell(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
